/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { DutchAuction } from "./DutchAuction";
export type { IERC20 } from "./IERC20";
export type { Lock } from "./Lock";
export type { Tree } from "./Tree";
export * as factories from "./factories";
export { DutchAuction__factory } from "./factories/DutchAuction__factory";
export type { ERC20 } from "./ERC20.sol/ERC20";
export { ERC20__factory } from "./factories/ERC20.sol/ERC20__factory";
export type { INNOShop } from "./ERC20.sol/INNOShop";
export { INNOShop__factory } from "./factories/ERC20.sol/INNOShop__factory";
export type { INNOToken } from "./ERC20.sol/INNOToken";
export { INNOToken__factory } from "./factories/ERC20.sol/INNOToken__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
export { Tree__factory } from "./factories/Tree__factory";
