/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TreeInterface extends Interface {
  getFunction(
    nameOrSignature: "encode" | "hashes" | "makeHash" | "verify"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "encode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "makeHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [string, BigNumberish, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "encode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface Tree extends BaseContract {
  connect(runner?: ContractRunner | null): Tree;
  waitForDeployment(): Promise<this>;

  interface: TreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encode: TypedContractMethod<[input: string], [string], "view">;

  hashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  makeHash: TypedContractMethod<[input: string], [string], "view">;

  verify: TypedContractMethod<
    [
      transaction: string,
      index: BigNumberish,
      root: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encode"
  ): TypedContractMethod<[input: string], [string], "view">;
  getFunction(
    nameOrSignature: "hashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "makeHash"
  ): TypedContractMethod<[input: string], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      transaction: string,
      index: BigNumberish,
      root: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
